spring:
  datasource:
    url: jdbc:h2:mem:evenly_test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  flyway:
    enabled: false   # simplest for now

  jpa:
    hibernate:
      ddl-auto: none
